// Do not edit. This file is machine generated by the Resource DLL Wizard.

library StoryGen;

{ITE} {DFMFileType} {FilePathes.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {DFMFileType} {OpenDialogExt.dfm}
{ITE} {DFMFileType} {Stats.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {YouNotSelectTheFile.dfm}
{ITE} {DFMFileType} {YourTextFileEncodeIsCorrupted.dfm}
{ITE} {RCFileType} {StoryGen_DRC.rc}

{$R 'FilePathes.dfm' FilePathAssociations:TForm}
{$R 'Main.dfm' MainForm:TForm}
{$R 'OpenDialogExt.dfm' OpenDialog:TForm}
{$R 'Stats.dfm' Statistics:TForm}
{$R 'Unit2.dfm' GenreForm:TForm}
{$R 'Unit3.dfm' EventsLists:TForm}
{$R 'YouNotSelectTheFile.dfm' NoSelectFile_ErrorForm:TForm}
{$R 'YourTextFileEncodeIsCorrupted.dfm' CurruptedEncoding_HelpFrame:TForm}
{$R 'StoryGen_DRC.res' 'StoryGen_DRC.rc'}

{$E ENU}

begin
end.
